### ISSUE TITLE
For playlists, get newly added videos first.

### ISSUE THREAD

**Issue by CarlosMFdz** [trevorsharp/youtubecast#2]
When creating a feed for a playlist that is sorted as oldest-to-newest, 
if the playlist has more than 50 videos you can never get updates for the newer videos,
since the most recent videos will always be outside of the max results of 50.
This could be fixed by generating the feed from the most recently added videos always,
regardless of the sort order that the playlist has.

**Comment by trevorsharp** [comment]
That is a great point! Unfortunately, YouTube's API doesn't provide an efficient solution to retrieve the latest items from a playlist if it isn't sorted by most recently added at the top. I was trying to avoid any excessive API usage by just looking at the first 50 items in a playlist, but it seems like to be more broadly compatible I will have to pull all the items in the playlist to find the most recently added items. 

I went ahead with this and added logic to find the most recently added ones whenever it looks like the playlist is not sorted by most recent already. Hopefully, the API usage is low enough that it won't cause any issues.

Let me know if the latest changes aren't solving your issue!

**Comment by CarlosMFdz** [comment]
That did the trick, thanks.

**Comment by trevorsharp** [comment]
Unfortunately, this has proven too costly to continue. Since it takes too many resources to collect all the elements of a playlist to find the newest ones, I have disabled this feature in the hosted version of this project. See the [README](https://github.com/trevorsharp/youtubecast#playlists-with-new-items-added-to-the-end) for more information on how to achieve this functionality with a self-hosted solution.
