### ISSUE TITLE
Support for feed filtering

### ISSUE THREAD

**Issue by 726a67** [trevorsharp/youtubecast#4]
Currently, feeds served by YouTubeCast will include any/all videos from their respective upstream sources (channel, playlist, etc.).

If possible, I'd love to see an ability to filter the feed results, similar to what you've done with `feed.filter` in [youtube-podcast-feeds](https://github.com/trevorsharp/youtube-podcast-feeds).

If not, no biggie -- as always, thanks for your work!

**Comment by trevorsharp** [comment]
I’ve got some plans for a new tool that modifies and filters podcast feeds. That tool’s goal will be to work with all kinds of podcast feeds. Once I have that completed, I would like to make it easy to create a new modified feed by linking to that tool after finding a feed. 

I think I’ll have some time soon-ish to work on that new tool, but until then I probably won’t add any feed modification or filtering tools into this project. Hopefully, the existing `youtube-podcast-feeds` project can work for you until then!

**Comment by 726a67** [comment]
Sure thing. The tool sounds interesting; I'll keep an eye out!

**Comment by trevorsharp** [comment]
## Update

I got around to making a new tool for filtering / modifying podcast feeds. It's called podmod. You can check it out at [podmod.app](https://podmod.app) or see the [code repository](https://github.com/trevorsharp/podmod.app).

In the future, I may add an option on the YouTubeCast UI for linking directly to podmod in order to start modifying a newly-generated feed.

**Comment by 726a67** [comment]
Awesome, I'll take a look!
