### ISSUE TITLE
Members only content

### ISSUE THREAD

**Issue by konopielko** [trevorsharp/youtubecast#7]
It would be a nice feature if you could also watch members only content (by subscribing to a playlist with member only videos) - this could be achieved by submitting your cookie value (https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js) when creating a new feed, then passing it the same way quality is being passed and then adding a cookie header:
`const videoInfo = await ytdl.getInfo("https://www.youtube.com/watch?v=${videoId}", {
    requestOptions: {
      headers: {
        cookie: cookie,
      },
    },
  });`

**Comment by trevorsharp** [comment]
I need to think through how to do this securely. I don't want to pass the cookie values in the feed URL as query parameters, since that would directly expose the cookie values to a user's podcast app, which could be problematic.

Right now, my [youtubecast-videoserver](https://github.com/trevorsharp/youtubecast-videoserver) project can take a cookie.txt file to support members-only content. But that currently only supports downloading the media to a self-hosted server. 

My initial thought is to modify the videoserver tool or create a similar tool that can work without having to download the videos. So if someone wants members-only content, they would have to self-host a version of this tool that can pull cookies from a file or from an environment variable. Then, the feed URL would only need the hostname of where to access this tool's API to generate the YouTube media file URLs.

This approach has the advantage of not needing to centrally store any user's cookies and not needing to embed the sensitive cookie data in the URL. Then when the cookies expire, the cookie values can be updated without needing to change the feed URL and having to re-add the feed to podcast apps.

Another idea would be to encrypt the cookie values using a secret key (provided to YouTubeCast as an environment variable) and put the encrypted cookies into the URL, which would then be able to be decrypted by the service when requesting a video. This approach has the benefit of not needing the user to run their own service, but it would require updating the feed URL whenever the cookies expire.

**Comment by trevorsharp** [comment]
## Solved

For anyone else looking to use members-only videos in a podcast feed, this now requires self-hosting this YouTubeCast project and setting the COOKIES environment variable to your own YouTube cookies for your own use. See the README for more information.
